package by.epam.carsharing.controller.command;

public enum CommandName {
    LOGIN,
    REGISTER,
    SIGNOUT,
    GOTOLOGINPAGE,
    GOTONEWSPAGE,
    GOTOREGISTERPAGE,
    GOTOCARSPAGE,
    GOTOCARCOMMENTSPAGE,
    CHANGELANG,
    GOTONEWSEDITPAGE,
    ADDNEWS,
    EDITNEWS,
    DELETENEWS,
    GOTOCAREDITPAGE,
    GOTOORDERPAGE,
    ADDCAR,
    EDITCAR,
    DELETECAR,
    GOTOORDERSPAGE,
    MAKEORDER,
    CHANGEORDERSTATUS,
    GOTOPAYMENTPAGE,
    MAKEPAYMENT,
    LEAVECOMMENT,
    DELETECOMMENT
}
